on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Run tests
      uses: cheesestraws/omnitalk_test_runner@master
      with:
        path: "omnitalk/"
    - name: Test report
      run: |
        cd omnitalk/main
        cat ${GITHUB_WORKSPACE}/run.log | perl report_on_tests.pl
