on:
  push:
    paths:
      - 'omnitalk/main/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: run tests
      uses: cheesestraws/omnitalk_test_runner

